// Generated by CoffeeScript 2.3.2
var c, dot, em, funcWrapper, hsla, pct, px, rgb;

funcWrapper = (funcName, argsCount) => {
  return (...args) => {
    var _args;
    if (args.length === 1) {
      if ((Array.isArray(args[0])) && (args[0].length === argsCount)) {
        _args = args[0];
      } else {
        _args = [args[0], args[0], args[0]];
      }
      return `${funcName}(${_args.join(', ')})`;
    } else {
      return `${funcName}(${args.join(', ')})`;
    }
  };
};

px = (n) => {
  return `${n}px`;
};

em = (n) => {
  return `${n}em`;
};

pct = (n) => {
  return `${n}%`;
};

dot = (n) => {
  return `.${n}`;
};

c = (...args) => {
  if (args.length === 1) {
    return args[0].join(' ');
  }
  return args.join(' ');
};

rgb = funcWrapper('rgb', 3);

hsla = funcWrapper('hsla', 4);

export {
  c,
  px,
  em,
  pct,
  dot,
  rgb,
  hsla
};

export default {c, px, em, pct, dot, rgb, hsla};
