// Generated by CoffeeScript 2.3.2
var HOCconcat, HOCfunc, cc, cs, dot, em, hsla, pct, px, rgb, rgba;

HOCfunc = (funcName, argsCount) => {
  return (...args) => {
    var _args;
    if (args.length === 1) {
      if ((Array.isArray(args[0])) && (args[0].length === argsCount)) {
        _args = args[0];
      } else {
        _args = [args[0], args[0], args[0]];
      }
      return `${funcName}(${_args.join(', ')})`;
    } else {
      return `${funcName}(${args.join(', ')})`;
    }
  };
};

HOCconcat = (concatName) => {
  return (...args) => {
    if (args.length === 1) {
      return args[0].join(concatName);
    }
    return args.join(concatName);
  };
};

px = (n) => {
  return `${n}px`;
};

em = (n) => {
  return `${n}em`;
};

pct = (n) => {
  return `${n}%`;
};

dot = (n) => {
  return `.${n}`;
};

rgb = HOCfunc('rgb', 3);

rgba = HOCfunc('rgba', 4);

hsla = HOCfunc('hsla', 4);

cs = HOCconcat(' ');

cc = HOCconcat(','); // Comma

export {
  cs,
  cc,
  px,
  em,
  pct,
  dot,
  rgb,
  rgba,
  hsla
};

export default {cs, cc, px, em, pct, dot, rgb, rgba, hsla};
