// Generated by CoffeeScript 2.3.2
import cfxvue from 'cfx.vue.vue';

import style from './style';

export default cfxvue('app', ({cfxify}) => {
  var c;
  c = cfxify({'div': 'div'});
  return c.div({}, c.div({
    attrs: {
      class: style.boxShadow
    }
  }), c.div({
    attrs: {
      class: style.outline
    }
  }), c.div({
    attrs: {
      class: style.outlineOffset
    }
  }));
});
