// Generated by CoffeeScript 2.3.2
import cfxvue from 'cfx.vue.vue';

import style from './style';

export default cfxvue('app', ({cfxify}) => {
  var c;
  c = cfxify({'div': 'div'});
  return c.div({
    attrs: {
      class: style
    }
  }, 'Hello World!!!');
});
