// Generated by CoffeeScript 2.3.1
import Vue from 'vue';

import cfxify from './cfx';

export default (ComponentName, Component) => {
  var componentType, getComponentRender;
  getComponentRender = (_Component) => {
    return (createElement) => {
      return _Component({
        cfxify: (waitToCfxify) => {
          return cfxify({createElement}, waitToCfxify);
        }
      });
    };
  };
  componentType = typeof Component;
  return Vue.component(ComponentName, componentType !== 'function' ? ((Component.render != null) && (componentType === 'function') ? {
    ...Component,
    render: getComponentRender(Component.render)
  } : Component) : {
    render: getComponentRender(Component)
  });
};
